### PR TITLE
Every new thing translated except those in an issue

### PR DESCRIPTION
**Pull request by r-a-jones**
Added translations of all the new biomes, lots of blocks, and a few other things. I'll try get [your program](https://github.com/LAntoine/chinese-subtitles-translator) to do the rest in a much nicer way when I have the time.

### CODE REVIEW

**Comment by r-a-jones** [comment]
See issue https://github.com/r-a-jones/chinese-for-learners-minecraft-language-pack/issues/1 for some things that have not been translated. Everything in game is translated (e.g. blocks, items, mobs) - these are GUI items

**Comment by r-a-jones** [comment]
Turns out the new features in 1.19.4 are still missing (e.g. the sniffer) - I'll add these later, but much more is translated here.

**Comment by L-Yvelin** [comment]
Hi! I'm amazed and very grateful for your work, do you plan to continue with the newer versions? If I wanted/could help, what's your process and your standards?

**Comment by LAntoine** [comment]
> Hi! I'm amazed and very grateful for your work, do you plan to continue with the newer versions? If I wanted/could help, what's your process and your standards?

I used microsoft translation API to do the transcription. To do that I used an application I made earlier to translate subtitles: https://github.com/LAntoine/chinese-subtitles-translator
To run it you need an azure secret key, if you have an azure account you can use it for free.

I will try to find some time to automate the process and publish new versions.

**Pull request merged**
